/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogListarGrupos.java
 *
 * Created on 31/05/2011, 21:54:03
 */
package br.edu.ifpi.ui;

import br.edu.ifpi.beans.Categoria;
import br.edu.ifpi.dao.CategoriaDao;
import br.edu.ifpi.factory.DaoFactory;
import java.util.ArrayList;
import java.util.Vector;
import javax.persistence.Table;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laerton
 */
public class DialogListarCategorias extends javax.swing.JDialog {

    CategoriaDao categoriaDao;
    DefaultTableModel model;

    /** Creates new form DialogListarGrupos */
    public DialogListarCategorias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        model = (DefaultTableModel) TabelaCategoria.getModel();
        categoriaDao = new DaoFactory().buildCateoriaDao();

        mountTableCategorias();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCategoria = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BotaoSair = new javax.swing.JButton();
        BotaoNovaCateg = new javax.swing.JButton();
        BotaoAlterar = new javax.swing.JButton();
        BotaoRemover = new javax.swing.JButton();
        CampoNomePesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BotaoPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Categorias de Compromissos");

        TabelaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome da Categoria"
            }
        ));
        jScrollPane1.setViewportView(TabelaCategoria);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BotaoSair.setText("Sair");
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        BotaoNovaCateg.setText("Novo");
        BotaoNovaCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovaCategActionPerformed(evt);
            }
        });

        BotaoAlterar.setText("Alterar");
        BotaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterarActionPerformed(evt);
            }
        });

        BotaoRemover.setText("Remover");
        BotaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoNovaCateg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(BotaoSair)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoNovaCateg)
                    .addComponent(BotaoAlterar)
                    .addComponent(BotaoSair)
                    .addComponent(BotaoRemover))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setText("Consultar:");

        BotaoPesquisar.setText("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CampoNomePesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoPesquisar))
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNomePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mountTableCategorias() {

       
        Vector v = null;

        ArrayList<Categoria> categorias = categoriaDao.list();

        if (categorias.size() > 0) {

            for (Categoria c : categorias) {
                v = new Vector();
                
                v.add(c);
                model.addRow(v);
            }
        }
        
        TabelaCategoria.setModel(model);
    }

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        dispose();
        
}//GEN-LAST:event_BotaoSairActionPerformed

    private void BotaoNovaCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovaCategActionPerformed
        DialogCategoria categ = new DialogCategoria(null, true, model);
        categ.setVisible(true);

        
    }//GEN-LAST:event_BotaoNovaCategActionPerformed

    private void BotaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRemoverActionPerformed
        int rows[] = TabelaCategoria.getSelectedRows();

        if (rows.length != -1) {

            int count = 0;
            for (int i = 0; i <= model.getRowCount(); i++) {

                if (i == rows[count]) {

                    Categoria c = (Categoria) TabelaCategoria.getValueAt(i, 0);

                    int conf = JOptionPane.showConfirmDialog(null, "você realmente quer excluir essa categoria? [" + c + "]");

                    if (conf == 0) {

                        categoriaDao.remove(c.getId());
                        JOptionPane.showMessageDialog(null, "categoria removida!");
                        model.removeRow(i);

                        if(!(count + 1 >= rows.length)){
                            count = count + 1;
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_BotaoRemoverActionPerformed

    private void BotaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAlterarActionPerformed


        Categoria c = (Categoria) TabelaCategoria.getValueAt(TabelaCategoria.getSelectedRow(), 0);

        if (c != null) {

            DialogCategoria categ = new DialogCategoria(null, true, categoriaDao, c);
            categ.setVisible(true);
        }

    }//GEN-LAST:event_BotaoAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogListarCategorias dialog = new DialogListarCategorias(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAlterar;
    private javax.swing.JButton BotaoNovaCateg;
    private javax.swing.JButton BotaoPesquisar;
    private javax.swing.JButton BotaoRemover;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JTextField CampoNomePesquisa;
    private javax.swing.JTable TabelaCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
