/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogContatos.java
 *
 * Created on 30/05/2011, 22:39:53
 */
package br.edu.ifpi.ui;

import br.edu.ifpi.beans.*;
import br.edu.ifpi.dao.GrupoDao;
import br.edu.ifpi.factory.DaoFactory;
import br.edu.ifpi.util.ComboboxUtil;


import java.text.ParseException;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Laerton
 */
public class DialogContatos extends javax.swing.JDialog {

    UsuarioLogado usuario;
    private MaskFormatter mascara;
    private int tipo = 0;
    private Contato contato;
    private DaoFactory daoFactory;
    private GrupoDao grupoDao;

    /** Creates new form DialogContatos */
    public DialogContatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setTipo(0);
        setLocationRelativeTo(null);
        contato = new Contato();
        daoFactory = new DaoFactory();
        grupoDao = daoFactory.buildGrupoDao();
        usuario = new UsuarioLogado();
        mountComboboxGrupos();
    }

    public DialogContatos(java.awt.Frame parent, boolean modal, Contato contato) {
        super(parent, modal);
        initComponents();
        daoFactory = new DaoFactory();
        grupoDao = daoFactory.buildGrupoDao();

        mountComboboxGrupos();

        CampoNome.setText(contato.getNome());
        CampoEmail.setText(contato.getEmail());
        CampoEndCEP.setText(contato.getEndereco().getCep());
        CampoEndCompl.setText(contato.getEndereco().getComplemento());
        CampoFone.setText((contato.getTelefone()));

        //ComboSelecGrupo.setSelectedItem(contato.getGrupos().);

        setLocationRelativeTo(null);

        this.contato = contato;


        setTipo(1);
        atualizarTela();
        usuario = new UsuarioLogado();
    }

    public void mountComboboxGrupos() {

        DefaultComboBoxModel m = ComboboxUtil.mountComboboxGrupos((DefaultComboBoxModel) ComboSelecGrupo.getModel(), grupoDao);

        ComboSelecGrupo.setModel(m);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CampoEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoFone = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CampoEndLograd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CampoEndNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CampoEndCEP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CampoEndCompl = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BotaoSalvarContato = new javax.swing.JButton();
        BotaoCancelarContato = new javax.swing.JButton();
        try{
            mascara = new MaskFormatter("##/##/####");
            mascara.setPlaceholderCharacter('_');
        }
        catch(ParseException excp){

        }
        CampoDataNasc = new javax.swing.JFormattedTextField();
        CampoDataNasc = new javax.swing.JFormattedTextField(mascara);
        ComboSelecGrupo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonRefreshGrupos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contato");

        jLabel1.setText("Nome:");

        jLabel2.setText("E-mail:");

        jLabel3.setText("Data de Nasc.:");

        jLabel4.setText("Fone:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel5.setText("Logradouro:");

        jLabel6.setText("Número:");

        jLabel7.setText("CEP.:");

        jLabel8.setText("Complemento:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoEndLograd, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoEndNum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoEndCEP, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoEndCompl, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CampoEndLograd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CampoEndNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CampoEndCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CampoEndCompl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BotaoSalvarContato.setText("Salvar");
        BotaoSalvarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarContatoActionPerformed(evt);
            }
        });

        BotaoCancelarContato.setText("Cancelar");
        BotaoCancelarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarContatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(BotaoSalvarContato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(BotaoCancelarContato)
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCancelarContato)
                    .addComponent(BotaoSalvarContato))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CampoDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDataNascActionPerformed(evt);
            }
        });

        jLabel9.setText("Selecionar Grupo:");

        jButton1.setText("criar nova");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonRefreshGrupos.setText("atualizar");
        jButtonRefreshGrupos.setEnabled(false);
        jButtonRefreshGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshGruposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CampoDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CampoFone)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboSelecGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRefreshGrupos)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CampoFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ComboSelecGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButtonRefreshGrupos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDataNascActionPerformed
}//GEN-LAST:event_CampoDataNascActionPerformed

    private void BotaoSalvarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarContatoActionPerformed



        if (tipo == 1) {
            if ((JOptionPane.showConfirmDialog(null, "Deseja confirmar alteração?", "Confirmar Alteração", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE)) == 0) {


                atualizarClasse();

                daoFactory.buildContatoDao().update(contato);

                dispose();
            } else {
                dispose();
            }
        } else if (tipo == 0) {
            if ((JOptionPane.showConfirmDialog(null, "Deseja confirmar inclusão?", "Confirmar Inclusão", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE)) == 0) {
                atualizarClasse();

                daoFactory.buildContatoDao().save(contato);

//                JOptionPane.showMessageDialog(null, "adicionando contato pro usuário: " + usuario.getUsuario().getUsername());
                //    JOptionPane.showMessageDialog(null, "adicionando contato pro usuário: " + ((Grupo) ComboSelecGrupo.getSelectedItem()).getId());

                addContatoToUsuario(contato.getId());
                contato = null;

                dispose();



            } else {
                dispose();
            }
        }
    }//GEN-LAST:event_BotaoSalvarContatoActionPerformed

    public void addContatoToUsuario(long id) {

        contato = new DaoFactory().buildContatoDao().getById(id);

        try {
            usuario.getUsuario().getContatos().add(contato);

            usuario.getUsuario().setContatos(usuario.getUsuario().getContatos());

            daoFactory.buildUsuarioDao().update(usuario.getUsuario());

            JOptionPane.showMessageDialog(null, "salvou: " + usuario.getUsuario().getContatos().size());
        } catch (Exception e) {
            System.out.println("e: " + e);
        }
    }

    private void BotaoCancelarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarContatoActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja cancelar esta operação?", "Confirme", JOptionPane.OK_OPTION);

        if (resposta == 0) {
            setContato(null);
            dispose();
        }
    }//GEN-LAST:event_BotaoCancelarContatoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DialogGrupo dialogGrupo = new DialogGrupo(null, true, grupoDao);
        dialogGrupo.setVisible(true);


        jButtonRefreshGrupos.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonRefreshGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshGruposActionPerformed


        mountComboboxGrupos();

        jButtonRefreshGrupos.setEnabled(false);
    }//GEN-LAST:event_jButtonRefreshGruposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogContatos dialog = new DialogContatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelarContato;
    private javax.swing.JButton BotaoSalvarContato;
    private javax.swing.JFormattedTextField CampoDataNasc;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoEndCEP;
    private javax.swing.JTextField CampoEndCompl;
    private javax.swing.JTextField CampoEndLograd;
    private javax.swing.JTextField CampoEndNum;
    private javax.swing.JTextField CampoFone;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JComboBox ComboSelecGrupo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRefreshGrupos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tipo
     */
    public int getTipo() {
        return tipo;
    }

    /**
     * @param tipo the tipo to set
     */
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }

    private void atualizarTela() {
        CampoNome.setText(contato.getNome());
        CampoEmail.setText(contato.getEmail());
        CampoDataNasc.setText(String.valueOf(contato.getDataNascimento()));
        CampoFone.setText(contato.getTelefone());
        CampoEndCEP.setText(contato.getEndereco().getCep());
        CampoEndCompl.setText(contato.getEndereco().getComplemento());
        CampoEndLograd.setText(contato.getEndereco().getNome());
        CampoEndNum.setText("" + contato.getEndereco().getNumero());

    }

    private void atualizarClasse() {


        Endereco ed = new Endereco();
        ed.setCep(CampoEndCEP.getText());
        ed.setComplemento(CampoEndCompl.getText());
        ed.setNome(CampoEndLograd.getText());

        if (!CampoEndNum.getText().equals("")) {

            ed.setNumero(Integer.parseInt(CampoEndNum.getText()));
        }

        Grupo g = (Grupo) ComboSelecGrupo.getSelectedItem();

        System.out.println("grupo: " + g.getNome());

        Set<Grupo> grupos = new HashSet<Grupo>();
        grupos.add(g);

        contato.setGrupos(grupos);
        this.contato.setEmail(CampoEmail.getText());
        this.contato.setEndereco(ed);
        this.contato.setNome(CampoNome.getText());
        this.contato.setTelefone(CampoFone.getText());

    }

    /**
     * @return the contato
     */
    public Contato getContato() {
        return contato;
    }

    /**
     * @param contato the contato to set
     */
    public void setContato(Contato contato) {
        this.contato = contato;
    }
}
