/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogGrupo.java
 *
 * Created on 01/06/2011, 16:58:29
 */
package br.edu.ifpi.ui;

import br.edu.ifpi.beans.Categoria;
import br.edu.ifpi.dao.CategoriaDao;
import br.edu.ifpi.factory.DaoFactory;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laerton
 */
public class DialogCategoria extends javax.swing.JDialog {

    CategoriaDao categoriaDao;
    Categoria categoria;
    boolean update = false;
    DefaultTableModel model;

    /** Creates new form DialogGrupo */
    public DialogCategoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        categoria = new Categoria();
    }

    public DialogCategoria(java.awt.Frame parent, boolean modal, CategoriaDao categoriaDao) {
        super(parent, modal);

        initComponents();
        setLocationRelativeTo(null);
        this.categoriaDao = categoriaDao;
        categoria = new Categoria();

    }

    public DialogCategoria(java.awt.Frame parent, boolean modal, DefaultTableModel model) {
        super(parent, modal);

        initComponents();
        setLocationRelativeTo(null);
//        this.categoriaDao = categoriaDao;

        categoria = new Categoria();
        this.model = model;
    }

    public DialogCategoria(java.awt.Frame parent, boolean modal, CategoriaDao categoriaDao, Categoria c) {
        super(parent, modal);

        initComponents();
        setLocationRelativeTo(null);
        this.categoriaDao = categoriaDao;
        this.categoria = c;

        CampoNomeCateg.setText(c.toString());
        update = true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CampoNomeCateg = new javax.swing.JTextField();
        BotaoSalvarCateg = new javax.swing.JButton();
        BotaoCancelarCateg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Nova Categoria");

        jLabel1.setText("Nome da Categoria:");

        CampoNomeCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeCategActionPerformed(evt);
            }
        });

        BotaoSalvarCateg.setText("Salvar");
        BotaoSalvarCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarCategActionPerformed(evt);
            }
        });

        BotaoCancelarCateg.setText("Cancelar");
        BotaoCancelarCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarCategActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CampoNomeCateg, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(BotaoSalvarCateg)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(BotaoCancelarCateg)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CampoNomeCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoCancelarCateg)
                    .addComponent(BotaoSalvarCateg))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNomeCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeCategActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeCategActionPerformed

    private void BotaoCancelarCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarCategActionPerformed
        dispose();
    }//GEN-LAST:event_BotaoCancelarCategActionPerformed

    private void BotaoSalvarCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarCategActionPerformed

        categoria.setNome(CampoNomeCateg.getText().trim());


        if (categoriaDao == null) {
            System.out.println("ta nulo!");
            categoriaDao = new DaoFactory().buildCateoriaDao();
        }

        if (!update) {
            categoriaDao.save(categoria);
            System.out.println("salvou!");
            CampoNomeCateg.setName("");

            Vector v = new Vector();
            v.add(categoria);
            model.addRow(v);

            this.setVisible(false);
        } else {

            categoriaDao.update(categoria);
        }
    }//GEN-LAST:event_BotaoSalvarCategActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogCategoria dialog = new DialogCategoria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelarCateg;
    private javax.swing.JButton BotaoSalvarCateg;
    private javax.swing.JTextField CampoNomeCateg;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
