/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogListContatos.java
 *
 * Created on 31/05/2011, 21:26:57
 */
package br.edu.ifpi.ui;

import br.edu.ifpi.beans.Contato;
import br.edu.ifpi.beans.UsuarioLogado;
import br.edu.ifpi.dao.ContatoDao;
import br.edu.ifpi.factory.DaoFactory;
import br.edu.ifpi.util.TableUtil;
import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laerton
 */
public class DialogListContatos extends javax.swing.JDialog {

    DaoFactory daoFactory;
    ContatoDao contatoDao;
    UsuarioLogado usuarioLogado;

    /** Creates new form DialogListContatos */
    public DialogListContatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);

        daoFactory = new DaoFactory();
        contatoDao = daoFactory.buildContatoDao();
        usuarioLogado = new UsuarioLogado();

        mountTabelaContatos();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CampoConsulta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ComboOpcaoConsulta = new javax.swing.JComboBox();
        BotaoPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaContatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BotaoAlterar = new javax.swing.JButton();
        BotaoImportaXML = new javax.swing.JButton();
        BotaoExportarXML = new javax.swing.JButton();
        BotaoRemover = new javax.swing.JButton();
        BotaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Contatos");

        jLabel1.setText("Consulta:");

        jLabel2.setText("Por:");

        ComboOpcaoConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "Data de Nasc", "Grupo", "Listar Todos" }));

        BotaoPesquisar.setText("Pesquisar");

        TabelaContatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "E-mail", "Fone", "Data de Nasc", "Endereço", "Grupo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaContatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaContatos);
        TabelaContatos.getColumnModel().getColumn(0).setResizable(false);
        TabelaContatos.getColumnModel().getColumn(1).setResizable(false);
        TabelaContatos.getColumnModel().getColumn(2).setResizable(false);
        TabelaContatos.getColumnModel().getColumn(3).setResizable(false);
        TabelaContatos.getColumnModel().getColumn(4).setResizable(false);
        TabelaContatos.getColumnModel().getColumn(5).setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BotaoAlterar.setText("Alterar");
        BotaoAlterar.setEnabled(false);
        BotaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterarActionPerformed(evt);
            }
        });

        BotaoImportaXML.setText("Importar XML");
        BotaoImportaXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoImportaXMLActionPerformed(evt);
            }
        });

        BotaoExportarXML.setText("Exportar XML");
        BotaoExportarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExportarXMLActionPerformed(evt);
            }
        });

        BotaoRemover.setText("Remover");
        BotaoRemover.setEnabled(false);
        BotaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRemoverActionPerformed(evt);
            }
        });

        BotaoSair.setText("Sair");
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoAlterar)
                .addGap(24, 24, 24)
                .addComponent(BotaoRemover)
                .addGap(18, 18, 18)
                .addComponent(BotaoImportaXML)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoExportarXML)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(BotaoSair)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoAlterar)
                    .addComponent(BotaoExportarXML)
                    .addComponent(BotaoImportaXML)
                    .addComponent(BotaoRemover)
                    .addComponent(BotaoSair))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(CampoConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(161, 161, 161))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboOpcaoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoPesquisar)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoPesquisar)
                    .addComponent(ComboOpcaoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mountTabelaContatos() {

        DefaultTableModel model = TableUtil.mountTableContatosUsuario((DefaultTableModel) TabelaContatos.getModel(), usuarioLogado.getUsuario());

        TabelaContatos.setModel(model);
    }

    private void BotaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAlterarActionPerformed
        int linha = TabelaContatos.getSelectedRow();

        Contato c = (Contato) TabelaContatos.getValueAt(linha, 0);

        DialogContatos dc = new DialogContatos(null, rootPaneCheckingEnabled, c);
        dc.setVisible(true);

    }//GEN-LAST:event_BotaoAlterarActionPerformed

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        dispose();
    }//GEN-LAST:event_BotaoSairActionPerformed

    private void TabelaContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaContatosMouseClicked

        BotaoAlterar.setEnabled(true);
        BotaoRemover.setEnabled(true);

        if (evt.getClickCount() == 2 && TabelaContatos.getSelectedRow() != -1) {

            JOptionPane.showMessageDialog(null, "linha: " + TabelaContatos.getColumnName(1));
        }
    }//GEN-LAST:event_TabelaContatosMouseClicked

    private void BotaoImportaXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoImportaXMLActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);

        fileChooser.setCurrentDirectory(new File("/contatos/imports/"));

        List<Contato> list = null;

        try {
            XStream xstream = new XStream(new DomDriver());

            list = (List<Contato>) xstream.fromXML(new FileReader(fileChooser.getSelectedFile()));

            JOptionPane.showMessageDialog(null, "carregou o arquivo: " + fileChooser.getSelectedFile().getName() + "com " + list.size() + " registros");

            mountTableFromImportedXML(list);
        } catch (FileNotFoundException ex) {

            Logger.getLogger(DialogListContatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoImportaXMLActionPerformed

    public void mountTableFromImportedXML(List<Contato> contatos) {

        DefaultTableModel model = (DefaultTableModel) TabelaContatos.getModel();

        Vector v = null;

        for (Contato c : contatos) {
        v = new Vector();

            v.add(c);
            v.add(c.getEmail());
            v.add(c.getTelefone());

            if (c.getDataNascimento() != null) {

                v.add(c.getDataNascimento());
            } else {

                v.add(null);
            }

            v.add(c.getEndereco().getNome());
            v.add(null);
            model.addRow(v);
        }
    }

    private void BotaoExportarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExportarXMLActionPerformed

        Set<Contato> contatos = usuarioLogado.getUsuario().getContatos();

        XStream xtream = new XStream();

        ArrayList<Contato> contatosList = new ArrayList<Contato>();

        for (Contato c : contatos) {

            contatosList.add(c);
        }

        String f = xtream.toXML(contatosList);

        try {

            BufferedWriter wr = new BufferedWriter(new FileWriter("contatos_exports/exported/contatos_" + usuarioLogado.getUsuario().getUsername() + ".xml"));

            wr.append(f);
            wr.close();

            JOptionPane.showMessageDialog(null, "Os dados foram exportados");
        } catch (IOException ex) {

            Logger.getLogger(DialogListContatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoExportarXMLActionPerformed

    private void BotaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRemoverActionPerformed

        int row[] = TabelaContatos.getSelectedRows();

        if (row.length != -1) {

            DefaultTableModel model = (DefaultTableModel) TabelaContatos.getModel();
            int c = 0;
            for (int i = 0; i <= model.getRowCount(); i++) {


                if (i == row[c]) {

                    Contato con = (Contato) TabelaContatos.getValueAt(i, 0);

                    usuarioLogado.getUsuario().getContatos().remove(con);
                    usuarioLogado.getUsuario().setContatos(usuarioLogado.getUsuario().getContatos());

                    int conf = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o Contato: " + c + "?");

                    if (conf == 0) {

                        new DaoFactory().buildUsuarioDao().update(usuarioLogado.getUsuario());

                        model.removeRow(i);

                        if (!(c + 1 >= row.length)) {

                            c = c + 1;
                        }
                    }
                }
            }
            JOptionPane.showMessageDialog(null, "contatos removidos");
        }
    }//GEN-LAST:event_BotaoRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogListContatos dialog = new DialogListContatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAlterar;
    private javax.swing.JButton BotaoExportarXML;
    private javax.swing.JButton BotaoImportaXML;
    private javax.swing.JButton BotaoPesquisar;
    private javax.swing.JButton BotaoRemover;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JTextField CampoConsulta;
    private javax.swing.JComboBox ComboOpcaoConsulta;
    private javax.swing.JTable TabelaContatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
