/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogGrupo.java
 *
 * Created on 01/06/2011, 16:58:29
 */
package br.edu.ifpi.ui;

import br.edu.ifpi.beans.Grupo;
import br.edu.ifpi.dao.GrupoDao;
import br.edu.ifpi.factory.DaoFactory;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laerton
 */
public class DialogGrupo extends javax.swing.JDialog {

    GrupoDao grupoDao;
    Grupo g;
    boolean update = false;
    DefaultTableModel model;

    public DialogGrupo(java.awt.Frame parent, boolean modal, GrupoDao grupoDao) {

        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.grupoDao = new DaoFactory().buildGrupoDao();

    }

    public DialogGrupo(java.awt.Frame parent, boolean modal, Grupo g) {

        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.grupoDao = new DaoFactory().buildGrupoDao();
        this.g = g;
        campoNomeGrupo.setText(g.toString());
        update = true;
    }

    public DialogGrupo(java.awt.Frame parent, boolean modal, DefaultTableModel model) {

        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.grupoDao = new DaoFactory().buildGrupoDao();
        this.model = model;
    }

    /** Creates new form DialogGrupo */
    public DialogGrupo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoNomeGrupo = new javax.swing.JTextField();
        BotaoSalvarGp = new javax.swing.JButton();
        BotaoCancelarGp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Novo Grupo");

        jLabel1.setText("Nome do Grupo:");

        campoNomeGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeGrupoActionPerformed(evt);
            }
        });

        BotaoSalvarGp.setText("Salvar");
        BotaoSalvarGp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarGpActionPerformed(evt);
            }
        });

        BotaoCancelarGp.setText("Cancelar");
        BotaoCancelarGp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarGpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(BotaoSalvarGp)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(BotaoCancelarGp)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoNomeGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(campoNomeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCancelarGp)
                    .addComponent(BotaoSalvarGp))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeGrupoActionPerformed

    private void BotaoCancelarGpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarGpActionPerformed

        dispose();
    }//GEN-LAST:event_BotaoCancelarGpActionPerformed

    private void BotaoSalvarGpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarGpActionPerformed


        if (!update) {
            g = new Grupo();

            g.setNome(campoNomeGrupo.getText().toString().trim());

            grupoDao.save(g);

            campoNomeGrupo.setText("");

            Vector v = new Vector();
            v.add(g);
            model.addRow(v);
            
            this.setVisible(false);
        } else {

            g.setNome(campoNomeGrupo.getText().toString().trim());
            grupoDao.update(g);
        }
    }//GEN-LAST:event_BotaoSalvarGpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogGrupo dialog = new DialogGrupo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelarGp;
    private javax.swing.JButton BotaoSalvarGp;
    private javax.swing.JTextField campoNomeGrupo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
