/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogListarGrupos.java
 *
 * Created on 31/05/2011, 21:54:03
 */
package br.edu.ifpi.ui;

import br.edu.ifpi.beans.Grupo;
import br.edu.ifpi.beans.UsuarioLogado;
import br.edu.ifpi.dao.GrupoDao;
import br.edu.ifpi.factory.DaoFactory;
import br.edu.ifpi.util.TableUtil;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Laerton
 */
public class DialogListarGrupos extends javax.swing.JDialog {

    GrupoDao gDao;
    DefaultTableModel modelo;

    /** Creates new form DialogListarGrupos */
    public DialogListarGrupos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        gDao = new DaoFactory().buildGrupoDao();
        mountTableGrupos();
    }

    public void mountTableGrupos() {

        modelo = TableUtil.mountTableGrupos((DefaultTableModel) TabelaGrupos.getModel(), gDao);

        if (modelo != null) {

            modelo.fireTableDataChanged();
        }

        TabelaGrupos.setModel(modelo);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaGrupos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BotaoSair = new javax.swing.JButton();
        BotaoNovo = new javax.swing.JButton();
        BotaoAlterarGrp = new javax.swing.JButton();
        BotaoRemoverGp = new javax.swing.JButton();
        CampoNomeGrupo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BotaoPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Grupos de Contatos");

        TabelaGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Grupo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaGrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaGruposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaGrupos);
        TabelaGrupos.getColumnModel().getColumn(0).setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BotaoSair.setText("Sair");
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        BotaoNovo.setText("Novo");
        BotaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovoActionPerformed(evt);
            }
        });

        BotaoAlterarGrp.setText("Alterar");
        BotaoAlterarGrp.setEnabled(false);
        BotaoAlterarGrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterarGrpActionPerformed(evt);
            }
        });

        BotaoRemoverGp.setText("Remover");
        BotaoRemoverGp.setEnabled(false);
        BotaoRemoverGp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRemoverGpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoAlterarGrp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoRemoverGp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(BotaoSair)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoNovo)
                    .addComponent(BotaoAlterarGrp)
                    .addComponent(BotaoSair)
                    .addComponent(BotaoRemoverGp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Consultar:");

        BotaoPesquisar.setText("Pesquisar");
        BotaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CampoNomeGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoPesquisar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNomeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        dispose();
}//GEN-LAST:event_BotaoSairActionPerformed

    public void editarGrupo() {

        int linha = TabelaGrupos.getSelectedRow();
        Grupo g = (Grupo) TabelaGrupos.getValueAt(linha, 0);
        DialogGrupo grupo = new DialogGrupo(null, true, g);
        grupo.setVisible(true);
    }

    private void BotaoAlterarGrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAlterarGrpActionPerformed
        editarGrupo();
    }//GEN-LAST:event_BotaoAlterarGrpActionPerformed

    private void BotaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoActionPerformed

        DialogGrupo g = new DialogGrupo(null, true, modelo);

        g.setVisible(true);
    }//GEN-LAST:event_BotaoNovoActionPerformed

    private void TabelaGruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaGruposMouseClicked

        BotaoNovo.setEnabled(true);
        BotaoRemoverGp.setEnabled(true);
        BotaoAlterarGrp.setEnabled(true);

        Grupo g = (Grupo) TabelaGrupos.getValueAt(TabelaGrupos.getSelectedRow(), 0);

        try {
            if (evt.getClickCount() == 2) {

                editarGrupo();
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_TabelaGruposMouseClicked

    public Grupo getGrupoByRow(int row) {

        Grupo grupo = null;

        if (row != -1) {

            try {

                grupo = (Grupo) TabelaGrupos.getValueAt(row, 0);

            } catch (Exception e) {
            }
        }

        return grupo;
    }

    private void BotaoRemoverGpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRemoverGpActionPerformed

        int row[] = TabelaGrupos.getSelectedRows();

        System.out.println("selecionados: "+row.length);

        if (row.length != -1) {

            int c = 0;

            for (int i = 0; i <= modelo.getRowCount(); i++) {

                if (i == row[c]) {

                    Grupo g = (Grupo) TabelaGrupos.getValueAt(i, 0);

                    int conf = JOptionPane.showConfirmDialog(null, "você quer excluir este grupo? [" + g + "]");

                    if (conf == 0) {

                        gDao.remove(g.getId());
                        JOptionPane.showMessageDialog(null, "grupo removido!");
                        modelo.removeRow(i);

                        if (!(c + 1 >= row.length)) {

                            c = c + 1;
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_BotaoRemoverGpActionPerformed

    private void BotaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPesquisarActionPerformed

        String argBusca = CampoNomeGrupo.getText();

        if (!argBusca.equals("")) {

            mountTableGrupos();
        } else {
        }
    }//GEN-LAST:event_BotaoPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogListarGrupos dialog = new DialogListarGrupos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAlterarGrp;
    private javax.swing.JButton BotaoNovo;
    private javax.swing.JButton BotaoPesquisar;
    private javax.swing.JButton BotaoRemoverGp;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JTextField CampoNomeGrupo;
    private javax.swing.JTable TabelaGrupos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
